apiVersion: v1
kind: Secret
metadata:
    name: appdaemon-ha-token
data:
    appdaemon-ha-token: ENC[AES256_GCM,data:15ESERmf9AOr/j1jElQsd5TOI4/e1awD3Q/SM78m2LeAXXt0hcbWvGHNPEK4BwXCjMJpSoEdXyvTrAQlZyTkrLs3Qs5G2Ki2RqjDl6G62AI2S5UENMmzglgRNy8ZbX51VolMRu+DwIEtSbbMydGwft8keqOBmODZeWmNlXeOEwpgRr2p38Wy/brm4Bcnqj9cd6geoh0lzKMmYvzMJ1jKkMmYzLpah1V7FO+1KHl7Sf3PdqpSU8IH,iv:IsLWI9roEnpBCSCf2MbeXSbIItXEQSw+Hfas+Woa8NE=,tag:8nx1c+4epexHpwPUXSuYiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gz9latge3y94hecqmjy3z9swp08c59pxy683uttfaqss0famtfzsr46nq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeldaaExjcXFOck1oYjZO
            aVZkMGZzdkZyWDllSjRlQ0xRNUQ4c2ZjVjB3CnpXVlgxckhQMFNjQ0kwclFvUHR6
            M2JRa1RCRWJMcHVsY1QycWZyZFBmcUUKLS0tIDN3TERnclNzQTRONjBMZ1VzbEpl
            SENTZXorQWw2VldYZkZ2dWVMc3VyT3MKviu4wm2ICWzL4tlsct/c0ors4biBpFRU
            yiD9QxWxwPlfv9rDmIYg/h+Ioruq4m4KpLcu1Jsxzos86huCmcHaAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T16:15:22Z"
    mac: ENC[AES256_GCM,data:OLJmNm2QwHfoiZxNAhywO82v37P7vtDaBUXFl4iXXHSoQQBWmeDuK/LE1q+rLGt2Yrb3b4SfspVeW0fcpRu5xa3IJ8DxX5YzZg5UrpgrkaVkrrMO+RExf5ZH4XtcVYC2GWRgwE+2vBzP5AGfPAqYUc+RPdjU/FHyYc0dWTa7F50=,iv:Ynq6fqyoBvgrosCFaIuR1OwGTXm7NMTOEKQAAg6IHDY=,tag:S0vbQBcty1ILQn28MBiuRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
