apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fluxcdbot
  name: fluxcdbot
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
  selector:
    app.kubernetes.io/name: fluxcdbot
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fluxcdbot
  labels:
    app.kubernetes.io/name: fluxcdbot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluxcdbot
  serviceName: fluxcdbot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluxcdbot
    spec:
      containers:
      - image: squat/fluxcdbot
        name: fluxcdbot
        args:
        - --token=$(TOKEN)
        - --url=http://fluxcdbot.flux-system.svc.cluster.local:8080
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: fluxcdbot
              key: token
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: internal
        volumeMounts:
        - name: data
          mountPath: /var/fluxcdbot
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/name: fluxcdbot
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
