apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: home-automation
  name: esphome
spec:
  ingressClassName: nginx
  rules:
  - host: esphome.tnorbert.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: esphome
            port:
              number: 6052
---
apiVersion: v1
kind: Service
metadata:
  namespace: home-automation
  name: esphome
spec:
  selector:
    app.kubernetes.io/name: esphome
  ports:
    - protocol: TCP
      port: 6052
      targetPort: 6052
