apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TTsWZDvfzEPvPofQKUA0bCJDZqpOYm+w,iv:SD0quWRTaik4Q6uV0iU9gNIW63tv6zs/dT06AC1JLwI=,tag:SFJt6+W2xboEu8LmYoPmZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17achrq2lfld3328ckkkkfp888yed4qe9vsks6n62437wvc5ntelsmkgymy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ0pibnhyTm5ldjNTWHhQ
            Rkk1YWNqZzgvS2dOYUpMVmpyK3U3Z1daMGxzClVXTkk4ak51Q3lJTDdsdFBFY1NW
            U1pEVzgzWE1ZU05VSStkb2RuWTFvSGsKLS0tIE55Q2t0QjBJbmo4aWZER0Jqdy9G
            VDJ2eWZDbHpDSFpFdzdpbUV6N2x5ZGsKZbriWUBbLdE8k+7EQSiszeyvy09TlcJ5
            H4QfgCL03fBioS/nF32ZrchWD0d0yZrNCDPzuKDx9kxHA3Y46Doy5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-17T18:24:38Z"
    mac: ENC[AES256_GCM,data:1lJDlt9Xz1eDpMM7dXoHyI6EB+RytYRDf60KMmNmBDXckwFoNcF36cbUmJoR7c5yu9tn0iAAj/wPslNV2TbRiD2v6daEi+K0il/kfZ9xzw791DHy7Yn4g95/dr+DP9ACHInRPDZZeE8MKOFGieoFkc6FGSdFxG831suQuoT8JLQ=,iv:AMCLeczptcpoGL65SEccwrp3y20dKxp5jVehS3VASW0=,tag:s6DOvGUjU+pWtpGPBFOQ5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
