---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./dnsendpoint-crd.yaml
  - ./secret.sops.yaml
  - ./pihole.sops.yaml
  - ./helmrelease.yaml
  - ./pihole-external-dns.yaml
