apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:0/R6J0mu9ltw8nAvKaX4tfnNsisZmZHz02j2CdH/PnJuOHgrAhX66w==,iv:2nVOWYo8YgWbjhOSuC7OxTvJXQ04IRBokvuT+LjxjBY=,tag:uqgcmVvgcJI1gG3FkB/ghg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17achrq2lfld3328ckkkkfp888yed4qe9vsks6n62437wvc5ntelsmkgymy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYkdWRkZFQUI0ODBMTjZ4
            Q2pMc1J4TUd5OU9hYlJyMThQZnlHZnl3V24wCmVqU2VpTjUzc2JsZ3pDVWprZktx
            QmlUZGx4UXREZWNDaTNlcjlmcmMvQ28KLS0tIGY1KzNFU3FHbHpzNTgzb3paQ1RV
            VVYrOEZCZWFwU0VacFF4blVjWkgyWWcKuxC2X7cE30nUuHfA2B9fqqqyIXado00b
            hrR2CjtQJ8tW0ezHk9KJVCW+PnCGFqeQI8Vlfz80TB+iTdRrBWFz5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-17T20:25:50Z"
    mac: ENC[AES256_GCM,data:0D/oEaWIEzDlSdQGKi7o6T4zWRPscu0SvqpP9nkkk7bDitP53IGqYKYkRDaEyS5wxs+wJS03YJwDQbzBh7ya3Pyw5h0PCM9tuYPNd6tbVJvHTNfPdtEUTDqx11GxTcW+998n6qyEjYm7SyxykrJrmbVQ/Tbvy5gW0eC6MK8TNS8=,iv:HxX06zFZVmtvdtSdCkcuLj+4gdY7CnXqj5fh+m5Nf78=,tag:30VoxNWlBR0EXQI99h1qYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
