apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:lBhtKz438lqxMG8eUXuXRrdn/JiOvHIQLDQjFg==,iv:L4JI73xqoWUM5SjJkcG77mwiatJhquQ7drxcLus1aD0=,tag:ucV9ezeADMG1TxKLRsXUZQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:E4KNv5bJD3iLW8FAhAlIHP+ihmDLofKF3g/rQB02onBh4GDB,iv:u4CGy7055vZlDoP4h4kwj1xW4ZvhsTYlZ+iInhkwT3s=,tag:z8T95YZwDjYrjnmk0q2ocg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:3Xf+ps6Rcbu8uOq1,iv:F7Ydr85nrwEBf5sqQcjcxInR3p2opv2gGx5k7loIAQw=,tag:MHzYXXXcET7M8qRKuhNUsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gz9latge3y94hecqmjy3z9swp08c59pxy683uttfaqss0famtfzsr46nq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINEl0bUw2dVlLU1hjQ29C
            azBJaVNNdjAxWk1ES1Arc1l0UmtvVExIaVUwCldtb2dsNURpZnRjSms0SHNCNTdK
            VXN1RitjVWM4N0FWNjdBQnhVN3FqcUUKLS0tIG5RWnFDQWs4djJuSWdCc0MwRm9W
            SmFzQlhhNFZwd1NHZ2llS0ZtWUNaSU0K+1vmvcNqNHfHinC8+RY6a/ktKUPX/EGY
            C9ZxgqgUusJDgRnNXGt8e6bl5v3k1BGFC2S3HcIIaFw0961sJVugiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-27T15:42:35Z"
    mac: ENC[AES256_GCM,data:st5OheNE7SvzSj3Fbw7suTEXRKYdOeie6f/Gvh5ZOmpxcmrvOUvVM0Sbsu1s46nSASffRoBk3/Q6ru3Ds5rPk6fgSvjaSdlYhSqTJcX4/6KaEhmAYc/7Dew151DQutJsr8EQFhPRaD6YAyZo2IYXpX2pqkSJ0mpFiOrxbgOmV0c=,iv:HAorHpAXdn4wyg/PCp5XF1mG93mp6GUvbDHUzMXeA14=,tag:V/OyeuNQtau/NG/eXwBObA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
