apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:s9iLiTWYv3yUGcsZf5bDzNiEK6iUOiwWEHGdb+kaEcHS4eES,iv:sSBvwjSMuy7padsE+R8ETJs71+K15x/XN1ZOlm7sgvA=,tag:KVOsFNcLpfUmnD/DSoBnTg==,type:str]
    credentials.json: ENC[AES256_GCM,data:gDdYEc9rUymI81oO0fFwkAZKFxXOr68Qt2JFaI6fqM7nq54HoDWcxLHRAfCqWeT1RqRbYHA46fvPX0E064AJ77wcBXV9Ps0Iap+caV2SUZjoXpODWL6gu1r93V9kqqHW2mZofVl7b53O3L/2EgTBuzzC7CASbQUUQhTlgho64HUg/hFeQ+8v6GFIsZWBcBSFl9XnNvJfExM/4XUjO5KESA/3jK6ZUyoOswj6uYKN9Q==,iv:2Zmg1QjZf+5RkKSGyt+/huStGLXXHxKDGuCcYzdZvOM=,tag:T9p/OBx07zVRLYEYM0zNJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gz9latge3y94hecqmjy3z9swp08c59pxy683uttfaqss0famtfzsr46nq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSlR1YVdMSE1jZnByYjV6
            YmxhZllLL05xZFltdkVxc3V1L0ZmRTJPZFVFCkw5aGYvU2VNa2gyK3JldnlNU0NC
            UGxBSDZ0Y0ZOZEs4OXZ2dDhmZzZ5c2cKLS0tIDhMY0NROVo0Zmo3YU5wUVBHbWhT
            RFdrbVBITG9lUWRtSTNqTlFibnpwOFkKLBtJ5OC1Y/eXxuSzKwv3jr1ftiXMBmBw
            Q/uO8bScG8O66WHerDykuLYNbTuBDfUzMadQoK+GljNWHhrRS3kVeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-27T15:42:35Z"
    mac: ENC[AES256_GCM,data:uKsfIRZp8l54ZgBSu6nc5s5hA4dffeRu9f+GRqXZscSYm6aA35wPSmi0PRadVfL1tK8Qdw7U9R9rCof33FzL56cv1vzN0WOjmZOHBjQBJGPadvPonLCClD1t1wXydg2qT7/HXrC3MODXSMEA/04BbOsOWA6va7aHm7XfL+16WQk=,iv:VLcGFgAJcPOpELc1zrSCuUCcUId7NK8G6wZonmswD9A=,tag:TLhsC4gRzJDYOC/nPCoZ8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
