apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:uSRBwKxV/tpKlNohyv3Zp1RaAacNa3oxP7XGQmC6kGmhefZl,iv:oMVj1ZkZpCE4dZK0imo50m6SyuhurWkK+ULumeIlICc=,tag:m8sNqx2Cka592Msvj989Mg==,type:str]
    credentials.json: ENC[AES256_GCM,data:NJSepHbJmoF/yz5PKCdS7pi7if+HaUBy7kPGwZlp67j7SFGCvfNwEAvtqkr+803W4krGp94uM/8avyl5dwIIsqiRpaA2euwyYSf9TG03cwAZJBgCVmo8v70L4aknk4tpfz1tDvMMbHdjdnEiQYKg+aNW3XC09dYLwSKbXCR6QlQoqDdc/WNQUhsI9CwvUJvLreO2yy+w/dQrZbIBjpeNZezEBVYAUX6EdC7PLX0C,iv:K+eNmT0l0IWJmPA6YhbR+JlBdi2jZQJm5m0eEpX6Kn0=,tag:7D3t+t4+kCLG6RvGXcrM1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17achrq2lfld3328ckkkkfp888yed4qe9vsks6n62437wvc5ntelsmkgymy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMFRZSUtMVHJ4NlVBbjNL
            ZHgzME5NVVhPSUxDbUNkL3ZBZ3JxQmpXWURnCmxHSkFvR2FlYzJFNGc0SXJqZ1FB
            R0lSTGtrTWdVV1ZlcWZ6ODAyY1J0QWcKLS0tIC9FWXBkbUlIdjNOeitRYjY0V05H
            T2c2R1hKU1dnMzRuMnMvTmFVRkQ2Q3MKiR8II0ZsDgTW/LrS/2yXfykbLbWhmDYD
            4Lt7reKyTWgKLRkFZDeTKaSfK2U/GkIM/AeZ9JPId9RSodLFfV8XSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-03T09:31:46Z"
    mac: ENC[AES256_GCM,data:Zf8D9b0HPyWp1+9Mwv8du5j/oh8r5P0xYnBMgwhVbvjA98kYKwYEogLcia/vZgym1SXULDJzM4KnWLnQTkecV81jrcfDvPltZycrA4e8Jug+afXRM7TUIAYxfdrOvyzlWuv3SMEwbhZ/+tQa9nioax2NSrw/FSrSZQyzkklKayw=,iv:xHbMdKRKyKvJ4mT9Wo6xQgxGoR7oOL786ybNNG3AIGM=,tag:YklnAxcmk5DJzGA6/g8h7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
