apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:8bT2iJmO8b7zfSepiNukwJzP3Qp+aqVVMGzrBz3BwNsj0qjY,iv:1gdU8phaVR1tbPxEEhFA86YgEInP5YeyXIjTinQVdAM=,tag:ihMLV7b5l4BxLT4uVaiqEQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:X8hBEIduvH8doSgFbzxbvoyRT/F7Xj61/Z0UvuZKX88U1lgRot5ofufYve/qXyGcO3t/IxuTg6Wx5M93sj3JtmSkaoiyKAdyu7K51duYJp5Gl4jx59kUklZIx7Qf7FvgsRxL66gnaF2do8QTUG5F0SBTZD+k8XD7C97f1el7LgQ7aLyrg9kZaGxw1LT1cUHQ+XNirBpRe92fuTgPb5EYmzuQr1E0rk/pb4Z8BfQNBw==,iv:qSNIQsEKHPSGHufM6isfQKX0I/tfkl2dFLBst5HW16I=,tag:oujS6t+YXjjc/F8ysaDlXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17achrq2lfld3328ckkkkfp888yed4qe9vsks6n62437wvc5ntelsmkgymy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaTlaU004cW1CKzVJMmNh
            a1ZDK2k4NkZyZmEyM29pTG1tY1FKS0NkRWtNCkFtSjBvSGcwWHlQbXB3Ukpvems3
            Nm05UFVBVGZ2NkxzbllxdFZiSU9DcW8KLS0tIEF4T0UwVzN6enJTVE1tWDY4Rytv
            OXBCL0tQUXpHSWNNN1JHM3hRUGZEQWcKG8cHHdcTqHvfrae9416/Xboc9RTQ469d
            djiegs9M9A54sR/iAHni0LXlXvqqj7MWnXZw3PgTjQlP4Nu++sfqFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T17:35:21Z"
    mac: ENC[AES256_GCM,data:FliLzS2X6atQWethHSW8T1ENwb3EEAX+E6alulGwMOBJQDE63Fe6Jz7+QvjN/VawmODjUA5RIkt5aUnwTTCekzX/2lpzWl93eG3dJwFmFYBRnB6BZoxYxZMAIE+slBqOvbkjSbNqsrSbab7JjEWOlagHjoekeBreLSILNzrNE/8=,iv:VA29zJRbBN2km4tt66n9wDuUcn3vCZF0JXRKW5zGSiQ=,tag:5VO45R2c+SImM57JSDaJBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
