apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-automation
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      volumes:
      - name: unraid-storage
        persistentVolumeClaim:
          claimName: unraid-pvc
      hostNetwork: false
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:2023.9
        envFrom:
        - configMapRef:
            name: home-assistant
        volumeMounts:
        - mountPath: "/config"
          subPath: home_assistant
          name: unraid-storage
ingress:
  main:
    enabled: true
    ingressClassName: external
    annotations:
      external-dns.alpha.kubernetes.io/target: "ha.${SECRET_DOMAIN}"
      hajimari.io/icon: video-input-antenna
    hosts:
      - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *host
