apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: home-automation
  name: home-assistant
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.tnorbert.com"
spec:
  ingressClassName: external
  rules:
  - host: ha.tnorbert.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-assistant
            port:
              number: 8123
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   namespace: home-automation
#   name: home-assistant
# spec:
#   ingressClassName: external
#   annotations:
#     external-dns.alpha.kubernetes.io/target: "home.${SECRET_DOMAIN}"
#     hajimari.io/icon: video-input-antenna
#   hosts:
#     - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
#       paths:
#         - path: /
#           pathType: Prefix
#   tls:
#     - hosts:
#       - *host
